jobs:
  # TODO
  build_linux:
    docker:
      docker:
        - image: cimg/base:2021.04
          auth:
            username: mydockerhub-user
            password: $DOCKERHUB_ACCESS_TOKEN
        steps:
          - run: echo "Hello world"

  build_macos:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

            brew install wget cmake
      - run:
          name: Build
          command: |
            chmod +x ./build.sh
            ./build.sh

workflows:
  version: 2
  commit:
    jobs:
      # TODO
      - build_linux:
          context: Docker credentials
      - build_macos
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      # TODO
      # - build_linux
      - build_macos
