jobs:
  build_linux:
    docker:
      - image: cimg/base:current
        auth:
          username: misp44
          password: $DOCKERHUB_ACCESS_TOKEN
    resource_class: small
    steps:
      - run:
          name: Build
          command: |
            chmod +x ./build.sh
            ./build.sh

  build_macos:
    macos:
      xcode: 12.5.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

            brew install wget cmake
      - run:
          name: Build
          command: |
            chmod +x ./build.sh
            ./build.sh

workflows:
  version: 2
  commit:
    jobs:
      - build_linux:
          context: Docker credentials
      # 
      # - build_macos
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build_linux
      - build_macos
